updated

diff --git a/.github/workflows/playwright-tests.yml b/.github/workflows/playwright-tests.yml
--- a/.github/workflows/playwright-tests.yml
+++ b/.github/workflows/playwright-tests.yml
@@ -21,9 +21,8 @@ jobs:
 
       - name: Clean previous Allure reports
         run: |
-          rm -rf allure-report
-          rm -rf allure-results
-          rm -rf docs/*  # Cleans the docs folder (be sure no important files are in it)
+          rm -rf allure-report allure-results docs/*
+          mkdir -p allure-results docs  # Ensure required directories exist
 
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
@@ -31,18 +30,17 @@ jobs:
       - name: Build and Run Playwright Tests in Docker
         run: |
           docker build -t playwright-tests .
-          docker run --rm -v $PWD/allure-results:/app/allure-results playwright-tests
+          docker run --rm -v $(pwd)/allure-results:/app/allure-results playwright-tests
 
       - name: Install Dependencies (Required for Allure Report)
         run: npm ci
 
       - name: Generate Allure Report
         run: |
-          npm run allure:generate
-          # Check if the allure-report folder is generated and has contents
-          ls allure-report || echo "Allure report not generated!"
-          mkdir -p docs  # Ensure the docs folder exists
-          mv allure-report/* docs/  # Move only the contents of allure-report
+          npm run allure:generate || echo "Allure report generation failed!"
+          ls -la allure-report || echo "Allure report folder is empty!"
+          mkdir -p docs
+          mv allure-report/* docs/ || echo "No files to move!"
 
       - name: Commit and Push Report
         run: |
@@ -55,6 +53,7 @@ jobs:
   upload_to_s3:
     needs: test
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -64,11 +63,13 @@ jobs:
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: eu-north-1
+          aws-region: us-east-1
+
+      - name: Remove old Allure Report from S3
+        run: aws s3 rm s3://testreportallure/ --recursive --region us-east-1
 
       - name: Upload Allure Report to S3
-        run: |
-          aws s3 cp docs/ s3://testreportallure/ --recursive --region us-east-1
+        run: aws s3 cp docs/ s3://testreportallure/ --recursive --region us-east-1
 
   notify:
     needs: upload_to_s3
@@ -77,7 +78,7 @@ jobs:
     steps:
       - name: Send Allure Report URL to Slack
         run: |
-          S3_URL="https://s3.us-east-1.amazonaws.com/testreportallure/index.html"
+          S3_URL="https://testreportallure.s3.amazonaws.com/index.html"
           curl -X POST -H 'Content-type: application/json' --data '{
           "text": "The latest Test Results Allure Report is available at: '"${S3_URL}"'"
            }' ${{ secrets.SLACK_WEBHOOK_URL }}
